# Generated by Django 3.2.3 on 2021-06-02 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_members_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('l_names', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro')], max_length=1)),
                ('b_date', models.DateField()),
                ('superior_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.empleado')),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
