# Generated by Django 3.2.3 on 2021-06-02 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210601_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito', models.FloatField()),
                ('c_disponible', models.FloatField()),
                ('saldo', models.FloatField()),
                ('dia_corte', models.IntegerField()),
                ('fecha_valida', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='D_tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('fecha_valida', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='empleado',
            name='superior_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.empleado'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('l_names', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro')], max_length=1)),
                ('ct_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.c_tarjeta')),
                ('dt_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.d_tarjeta')),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.empleado')),
            ],
        ),
    ]
