# Generated by Django 3.2.3 on 2021-06-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210602_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='emp_id',
            new_name='works_with',
        ),
        migrations.AddField(
            model_name='cliente',
            name='b_date',
            field=models.DateField(null=True),
        ),
    ]
