# Generated by Django 3.2.3 on 2021-06-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210602_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='superior_id',
            field=models.ForeignKey(blank=True, default='Gerente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.empleado'),
        ),
    ]
