# Generated by Django 3.2.3 on 2021-06-02 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_empleado_superior_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='superior_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.empleado'),
        ),
    ]
