# Generated by Django 3.2.3 on 2021-06-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_c_tarjeta_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_tarjeta',
            name='c_disponible',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='c_tarjeta',
            name='saldo',
            field=models.FloatField(null=True),
        ),
    ]
