# Generated by Django 3.2.3 on 2021-06-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20210602_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_tarjeta',
            name='c_disponible',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='c_tarjeta',
            name='saldo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
