# Generated by Django 3.2.3 on 2021-06-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_d_tarjeta_cliente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_tarjeta',
            name='cliente_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.cliente'),
        ),
    ]
